spring:
  application:
    name: discovery

  cloud:
    loadbalancer:
      ribbon:
        enabled: false


server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    renewal-percent-threshold: 0.85